template:
  name: CME Deploy Service To Environment V2
  identifier: CME_Deploy_Service_To_Environment_V2
  type: Stage
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      environment:
        environmentRef: <+input>
        deployToAll: false
        environmentInputs: <+input>
        serviceOverrideInputs: <+input>
        infrastructureDefinitions: <+input>
      service:
        serviceRef: <+input>
        serviceInputs: <+input>
      execution:
        steps:
          - step:
              name: xc
              identifier: xc
              template:
                templateRef: account.csd
                versionLabel: v2
          - parallel:
              - stepGroup:
                  name: testt
                  identifier: test
                  template:
                    templateRef: account.testSG1
                    versionLabel: v1
              - stepGroup:
                  name: stablesg
                  identifier: stablesg
                  template:
                    templateRef: account.testSG1
          - stepGroup:
              name: tesstt
              identifier: tesstt
              template:
                templateRef: account.testSG
                versionLabel: v1
        rollbackSteps:
          - step:
              name: Rollback Rollout Deployment
              identifier: rollbackRolloutDeployment
              type: K8sRollingRollback
              timeout: 10m
              spec:
                pruningEnabled: false
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: StageRollback
    timeout: 100m
  versionLabel: V2
