---
pipeline:
  projectIdentifier: "DoNotDelete_Mayank"
  orgIdentifier: "Ng_Pipelines_K8s_Organisations"
  tags: {}
  stages:
  - stage:
      name: "te"
      identifier: "te"
      description: ""
      type: "Custom"
      spec:
        execution:
          steps:
          - step:
              type: "HarnessApproval"
              name: "HarnessApproval_1"
              identifier: "HarnessApproval_1"
              spec:
                approvalMessage: "<+pipeline.resumedExecutionId>"
                includePipelineExecutionHistory: true
                isAutoRejectEnabled: false
                approvers:
                  userGroups:
                  - "account._account_all_users"
                  minimumCount: 1
                  disallowPipelineExecutor: false
                approverInputs: []
              timeout: "1d"
      tags: {}
  identifier: "rishabhtest_Clone"
  name: "rishabh-test - Clone"
