pipeline:
  name: rt
  identifier: rt
  projectIdentifier: testview
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: df
        identifier: df
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: c
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
