pipeline:
  name: test12
  identifier: test12
  projectIdentifier: rishabh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: tezt
        identifier: tezt
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: e2
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
