pipeline:
  projectIdentifier: Elastic
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: app
        identifier: app
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1a
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
        tags: {}
        when:
          pipelineStatus: Success
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
    - stage:
        name: t
        identifier: t
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: approval_Clone_Clone
          project: Elastic
  identifier: approval_Clone
  name: approval - Clone
