pipeline:
  projectIdentifier: CustomerPipelines
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: shel
        identifier: shel
        description: dddjjjmzt
        type: Custom
        sendGitStatus:
          enabled: true
          name: hello
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: Http_1
                  identifier: Http_1
                  spec:
                    url: https://www.google.com
                    method: GET
                    headers: []
                    inputVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - localdelegate
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "HEllo this is a simple script"

                          mv /harness /tmp/harness

                          echo "Done"

                          echo <+pipeline.name>
                          echo <+secrets.getValue("test")>
                    environmentVariables:
                      - name: env
                        type: String
                        value: a,b
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: cd
        identifier: cd
        description: ""
        type: Deployment
        spec:
          deploymentType: CustomDeployment
          customDeploymentRef:
            templateRef: account.dtV1
            versionLabel: v1
          execution:
            steps:
              - step:
                  name: Fetch Instances
                  identifier: fetchInstances
                  type: FetchInstanceScript
                  timeout: 10m
                  spec: {}
            rollbackSteps: []
          service:
            serviceRef: account.dtv1
          environment:
            environmentRef: account.prodEnvWithoutFreeze
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dtv1
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  identifier: tagstest_git
  name: tagstest_git
