pipeline:
  name: ZTS TC05 Nested step groups
  identifier: zts_tc05_nested_stepgroups
  projectIdentifier: ZTS
  orgIdentifier: default
  description: Step groups nested inside step groups
  tags: {}
  stages:
    - stage:
        name: st1
        identifier: st1
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: outer
                  identifier: outer
                  steps:
                    - step:
                        name: o1
                        identifier: o1
                        type: ShellScript
                        timeout: 10m
                        spec:
                          shell: Bash
                          onDelegate: true
                          source:
                            type: Inline
                            spec:
                              script: echo zts
                    - stepGroup:
                        name: inner
                        identifier: inner
                        steps:
                          - step:
                              name: i1
                              identifier: i1
                              type: ShellScript
                              timeout: 10m
                              spec:
                                shell: Bash
                                source:
                                  type: Inline
                                  spec:
                                    script: echo zts
                                executionTarget: {}
                                environmentVariables: []
                                outputVariables: []
                              when:
                                stageStatus: All
                                condition: 1==0
                          - step:
                              name: i2
                              identifier: i2
                              type: ShellScript
                              timeout: 10m
                              spec:
                                shell: Bash
                                onDelegate: true
                                source:
                                  type: Inline
                                  spec:
                                    script: echo zts
