pipeline:
  name: ZTS TC10 Stage rollback steps
  identifier: zts_tc10_stage_rollback
  projectIdentifier: ZTS
  orgIdentifier: default
  description: Stage rollback steps (StageRollback failure strategy)
  tags: {}
  stages:
    - stage:
        name: st1
        identifier: st1
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: deploy
                  identifier: deploy
                  type: ShellScript
                  timeout: 10m
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: echo zts
                    executionTarget: {}
                    environmentVariables: []
                    outputVariables: []
              - stepGroup:
                  name: test
                  identifier: test
                  steps:
                    - step:
                        type: ShellScript
                        name: ShellScript_5
                        identifier: ShellScript_5
                        spec:
                          shell: Bash
                          executionTarget: {}
                          source:
                            type: Inline
                            spec:
                              script: echo 1
                          environmentVariables: []
                          outputVariables: []
                        timeout: 10m
              - parallel:
                  - step:
                      name: deploy1
                      identifier: deploy1
                      type: ShellScript
                      timeout: 10m
                      spec:
                        shell: Bash
                        source:
                          type: Inline
                          spec:
                            script: |-
                              echo zts
                              exit 1
                        executionTarget: {}
                        environmentVariables: []
                        outputVariables: []
                    contextType: Pipeline
                  - step:
                      name: deploy2
                      identifier: deploy2
                      type: ShellScript
                      timeout: 10m
                      spec:
                        shell: Bash
                        source:
                          type: Inline
                          spec:
                            script: |-
                              echo zts
                              exit 1
                        executionTarget: {}
                        environmentVariables: []
                        outputVariables: []
              - step:
                  name: deploy3
                  identifier: deploy3
                  type: ShellScript
                  timeout: 10m
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo zts
                          exit 1
                    executionTarget: {}
                    environmentVariables: []
                    outputVariables: []
                  strategy:
                    matrix:
                      a:
                        - c
                        - d
                        - e
                      b:
                        - f
                        - g
            rollbackSteps:
              - step:
                  name: rb_deploy
                  identifier: rb_deploy
                  type: ShellScript
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo zts
              - step:
                  name: rb_deploy2
                  identifier: rb_deploy2
                  type: ShellScript
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo zts
