pipeline:
  name: ZTS TC13 Retry failure strategy
  identifier: zts_tc15_retry
  projectIdentifier: ZTS
  orgIdentifier: default
  description: "Retry: step fails and is retried"
  tags: {}
  stages:
    - stage:
        name: st1
        identifier: st1
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: s1
                  identifier: s1
                  type: ShellScript
                  timeout: 10m
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: exit 1
                    executionTarget: {}
                    environmentVariables: []
                    outputVariables: []
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Retry
                          spec:
                            retryCount: 2
                            retryIntervals:
                              - 1s
                            onRetryFailure:
                              action:
                                type: Ignore
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
