pipeline:
  name: ZTS TC17 Ignore failure strategy
  identifier: zts_tc17_ignore
  projectIdentifier: ZTS
  orgIdentifier: default
  description: "Ignore failure strategy"
  tags: {}
  stages:
    - stage:
        name: st1
        identifier: st1
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: s1
                  identifier: s1
                  type: ShellScript
                  timeout: 10m
                  spec: {shell: Bash, onDelegate: true, source: {type: Inline, spec: {script: echo zts}}}
                  failureStrategies:
                    - onFailure:
                        errors: [AllErrors]
                        action:
                          type: Ignore
              - step: {name: s2, identifier: s2, type: ShellScript, timeout: 10m, spec: {shell: Bash, onDelegate: true, source: {type: Inline, spec: {script: echo zts}}}}
