pipeline:
  name: ZTS TC14 Step when stageStatus and JEXL
  identifier: zts_tc22_when_jexl
  projectIdentifier: ZTS
  orgIdentifier: default
  description: "Step when: stageStatus + JEXL condition"
  tags: {}
  stages:
    - stage:
        name: st1
        identifier: st1
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: s2
                  identifier: s2
                  type: ShellScript
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo zts
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.run> == "yes"
              - step:
                  name: s1
                  identifier: s1
                  type: ShellScript
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo zts
  variables:
    - name: run
      type: String
      value: "yes"
