pipeline:
  name: ZTS TC15 Stage when pipelineStatus
  identifier: zts_tc23_stage_when_pipelinestatus
  projectIdentifier: ZTS
  orgIdentifier: default
  description: "Stage when: pipelineStatus condition"
  tags: {}
  stages:
    - stage:
        name: st1
        identifier: st1
        type: Custom
        spec:
          execution:
            steps:
              - step: {name: a1, identifier: a1, type: ShellScript, timeout: 10m, spec: {shell: Bash, onDelegate: true, source: {type: Inline, spec: {script: echo zts}}}}
    - stage:
        name: st2
        identifier: st2
        type: Custom
        when:
          pipelineStatus: Success
          condition: "<+pipeline.variables.run> == \"yes\""
        spec:
          execution:
            steps:
              - step: {name: a2, identifier: a2, type: ShellScript, timeout: 10m, spec: {shell: Bash, onDelegate: true, source: {type: Inline, spec: {script: echo zts}}}}
  variables:
    - name: run
      type: String
      value: "yes"
