pipeline:
  name: cdpipegittemp
  identifier: cdpipegittemp
  tags: {}
  template:
    templateRef: pipetemp
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: ci
            template:
              templateInputs:
                type: CI
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: runstpaccountt
                          template:
                            templateInputs:
                              type: Run
                              spec:
                                image: <+input>.default(harness/todolist-sample).selectOneFrom(library/nginx,harness/todolist-sample)
                      - step:
                          identifier: rnustep
                          template:
                            templateInputs:
                              type: Run
                              spec:
                                image: <+input>.default(harness/todolist-sample).selectOneFrom(library/nginx,harness/todolist-sample)
  projectIdentifier: rishabh
  orgIdentifier: default
