pipeline:
  stages:
    - stage:
        name: Deploy to QA
        identifier: deploy_to_qa
        type: Deployment
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
          environment:
            environmentRef: <+input>
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  identifier: k8s_rolling_deploy
                  name: K8s Rolling Deploy
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    pruningEnabled: false
                    skipDryRun: false
            rollbackSteps:
              - step:
                  identifier: k8s_rolling_rollback
                  name: K8s Rolling Rollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
    - stage:
        name: Deploy to Production
        identifier: deploy_to_production
        type: Deployment
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
          environment:
            environmentRef: Production
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  identifier: k8s_rolling_deploy
                  name: K8s Rolling Deploy
                  type: K8sRollingDeploy
                  timeout: <+input>
                  spec:
                    pruningEnabled: true
                    skipDryRun: false
            rollbackSteps:
              - step:
                  identifier: k8s_rolling_rollback
                  name: K8s Rolling Rollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
    - stage:
        name: Hello World
        identifier: Hello_World
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo Hello World
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
              - step:
                  type: ShellScript
                  name: QA env Changes
                  identifier: QA_env_Changes
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 'QA env Changes'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: Harness Approval
        identifier: Harness_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Admin Approval
                  identifier: Admin_Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
  tags:
    ai_generated: "true"
  projectIdentifier: hackweek
  orgIdentifier: default
  identifier: Deploy_to_QA_and_Prod
  description: This pipeline was generated by Harness AI on 2025-06-03 14:15:55 UTC.
  name: Deploy to QA and Prod
